server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    mvc:
      path match:
        matching-strategy: ant_path_matcher
    messages:
      basename: messages